[package]
name = "delf"
version = "0.1.0"
edition = "2021"

[dependencies]
derive-try-from-primitive = "1.0.0"
derive_more = { version = "1.0.0", features = ["full"] }
enumflags2 = "0.7.10"
nom = "7.1.3"
